version: "3"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5432:5432"

  dict:
    build: .
    command: sh -c "python main.py"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      
volumes:
  pgdata: